/**  This file has been generated by zcontent utilities generator version 1.0-1
 using dictionary file /home/gerard/Development/zbasetools/zcontent/ztest_zindexedfile/testdata/zcppgenerateparameters.xml
 Generation date 2022-11-19 15:28:32

Attention: This file must not be manually changed in order to preserve the ability to change it using dictionary generation facilities.
-----------*/

#ifndef ZDOCPHYSICAL_H
#define ZDOCPHYSICAL_H

#include <sys/types.h>
#include <ztoolset/zlimit.h>
#include <ztoolset/ztypetype.h>
#include <ztoolset/zdatabuffer.h>
#include <ztoolset/zarray.h>
/*      private include files        */
#include <ztoolset/zbitset.h>
/*      local include files          */
#include <zcontentcommon/zresource.h>
#include <stdint.h>
#include <ztoolset/uristring.h>
#include <ztoolset/zdate.h>
#include <zcrypt/checksum.h>

/** @brief ZDocPhysical Physical document */

class ZDocPhysical {
private:
   ZBitset     FieldPresence;
public:

    ZResource Documentid /*!< Physical document unique identifier */;
    uint64_t DataRank;
    int64_t DocMetaType /*!< Document meta type i. e. mail, text document, etc. (see DocumentMetaType) */;
    int64_t Storage /*!< Category of storage : disk or other */;
    uriString URI /*!< Unique Resource descriptor of genuine file for document */;
    uint64_t DocSize;
    ZDateFull Registrated;
    ZDateFull Created;
    ZDateFull LastModified;
    ZResource OwnerOrigin;
    uint32_t AccessRights;
    checkSum CheckSum;
    uint8_t Temporary;
    ZResource Ownerid;
    ZResource Vaultid;
/* Public methods */
   ZDocPhysical()=default;
   ZDocPhysical& _copyFrom(const ZDocPhysical& pIn);
   ZDocPhysical& operator = (const ZDocPhysical& pIn) { return _copyFrom(pIn); }
   ZDataBuffer toRecord();
   ZStatus fromRecord(const ZDataBuffer& pRecord);
   zbs::ZArray<ZDataBuffer> getAllKeys();
   inline long getKeysNumber() { return 0; }
   /* Keys definition */
   ZDataBuffer       getKey(long pKeyNumber) ;
   utf8VaryingString getKeyName(long pKeyNumber) ;
}; // ZDocPhysical 
#endif //ZDOCPHYSICAL_H
